### ISSUE TITLE
Running jobs in a container using GitHub pipelines

### ISSUE THREAD

**Issue by anastasiyagromova** [microsoft/mlops-promptflow-prompt#61]
- create pipeline to build and push container image to Azure Container Registry
- update PR pipeline to use image and run jobs
- update CI pipeline to use image and run jobs

NOTE: GitHub Actions does not support directly referencing secrets in the container field
- https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

**Comment by sbaidachni** [comment]
It doesn't look easy to implement. Let's remove it from our backlog
